### ISSUE TITLE
inferior-ruby-mode: Symbol's function definition is void: ruby-mode-variables

### ISSUE THREAD

**Issue by hadronzoo** [jacott/Enhanced-Ruby-Mode#1]
When using Enhanced-Ruby-Mode with the latest official ruby-mode from the svn trunk, I get the following error when executing `M-x run-ruby`:

`inferior-ruby-mode: Symbol's function definition is void: ruby-mode-variables`

The `*ruby*` buffer is still created and irb is loaded, but Emacs does not automatically display the buffer. When Enhanced-Ruby-Mode is not being used, this error does not occur.

**Comment by hadronzoo** [comment]
Note: adding `(defun ruby-mode-variables () nil)` to my .emacs file fixes the issue.

**Comment by jacott** [comment]
I have added ruby-mode-variables to ruby-mode.el. You will need to remove your .emacs fix or else it may break with the new version.
