### ISSUE TITLE
Custom keywords

### ISSUE THREAD

**Issue by asok** [jacott/Enhanced-Ruby-Mode#12]
With ruby-mode I was able to do something like this:  `(font-lock-add-keywords 'ruby-mode '(("\\<\\(require_relative\\|require\\|include\\|extend\\)\\>" . font-lock-keyword-face)))`

But not in erm. It looks like it is working just for a seconds - when I edit buffer the font color changes but just after a second it goes back to default.

Is it possible to add custom keywords in erm?

**Comment by jacott** [comment]
erm does not really use font-lock so `font-lock-add-keywords` will not work.

I have added a new custom variable `ruby-extra-keywords`. After changing it you need to call the `erm-reset` function

I hope this suites your needs

Geoff

**Comment by asok** [comment]
Thanks a lot. Just a quick question: is there any way to set extra keywords per buffer (not globally). I was thinking about adding extra keywords to buffers with rspec-mode enabled.

**Comment by jacott** [comment]
Done. See doc on ruby-extra-keywords for details
