### ISSUE TITLE
slowness on newline

### ISSUE THREAD

**Issue by mbriggs** [jacott/Enhanced-Ruby-Mode#13]
love the mode, but I am finding when I make a newline (hit enter), there is a noticeable pause. strange, because I don't get any slowdown when doing any other kind of edit.

**Comment by jacott** [comment]
Hi Matt

I'm too busy to take a proper look but if you look at the function
`ruby-indent-line' and comment out the`(erm-wait-for-parse)' call it
should speed things up for you.
The side affect is that sometimes it might get the indenting wrong.

Hope that helps

Geoff

On 5 July 2012 06:21, Matt Briggs <
reply@reply.github.com

**Comment by mbriggs** [comment]
Yup, that worked for me :) Thanks for the help, this mode is about a billion times better then the official one. Going to open a few feature requests for stuff I would like to see, will probably take a crack at them myself if I can squeeze in the time (unlikely in the near future)
