### ISSUE TITLE
Feature Request: Moar Faces

### ISSUE THREAD

**Issue by mbriggs** [jacott/Enhanced-Ruby-Mode#14]
I love that you have string delimiters and operators, some things I would like to see (and would customize) are
- square brackets []
- parens ()
- brace brackets {}
- dots .
- colons :

I like to make dots, colons, and parens fade into the background a bit (makes things look kind of smalltalk-ish), and give different colors for arrays and hashes

**Comment by zenspider** [comment]
Please reopen this on my fork and close this one. Thanks.
