### ISSUE TITLE
Bug: Deep indentation for params is off by 1

### ISSUE THREAD

**Issue by mbriggs** [jacott/Enhanced-Ruby-Mode#15]
indentation is SO much better then official ruby-mode it is like a dream. The one issue I have noticed is if you type out this line

``` ruby
blah = foo(bin: 1,
          baz: 2)
```

you will see when you hit enter, the b in baz is lined up with the open paren of the arg list. If you indent the second line, it lines up fine, and if the whole line exists first and you hit enter right after the comma, it also indents fine.

**Comment by zenspider** [comment]
I believe this is fixed in my fork. Yup. Just tested it. Please close.
