### ISSUE TITLE
Feature Request: More fine grained control over warnings

### ISSUE THREAD

**Issue by mbriggs** [jacott/Enhanced-Ruby-Mode#16]
I love warnings, but one thing that is bugging me is that in rspec, this is how you do an assertion

``` ruby
foo.should == 1
```

you get as a warning

```
warning: possibly useless use of == in void context
```

I would rather have that then turn them off altogether, but it would be cool if there were some way to squelch certain warnings in certain buffers.

**Comment by JEG2** [comment]
This is an issue with RSpec, not this major mode.  They know it and are trying to correct it.  That's why RSpec now supports:

```
…should eq(…)
```

and:

```
expect(…).to eq(…)
```

**Comment by zenspider** [comment]
There is nothing to do in the mode. Please close this.
