### ISSUE TITLE
mmm-mode

### ISSUE THREAD

**Issue by asok** [jacott/Enhanced-Ruby-Mode#19]
When using erm with https://github.com/purcell/mmm-mode/blob/master/mmm-erb.el the ruby code in erb files does not have syntax highlighting. Anyone had more luck with mmm-mode?

**Comment by dgutov** [comment]
Since this mode hijacks the `ruby-mode` package, many things can go wrong. It provides the feature, but doesn't define many of the variables, so the font-locking code breaks when it tries use them.

zenspider's fork should work fine.

**Comment by asok** [comment]
In fact it does not fontifies the ruby parts neither. Though I guess the standard `ruby-mode` is sufficient for me in the `erb` files. Thanks.
