### ISSUE TITLE
this breaks haml-mode

### ISSUE THREAD

**Issue by nilclass** [jacott/Enhanced-Ruby-Mode#2]
_Messages_ Buffer shows

```
Error during redisplay: (void-variable ruby-font-lock-keywords) [2 times]
```

it used to work with default ruby-mode (from upstream ruby source)

**Comment by jacott** [comment]
Sorry but it looks like haml-mode depends on the internal workings of ruby-mode.

You could try requiring the original ruby-mode before loading my ruby-mode:

  (load-file "path-to-old/ruby-mode.el") ; load original ruby-mode
  (load-library "ruby-mode"); load enhanced-ruby-mode

**Comment by nilclass** [comment]
thanks, this actually works :)
