### ISSUE TITLE
Syntax Highlighting and Indenting Not Working

### ISSUE THREAD

**Issue by terryfinn** [jacott/Enhanced-Ruby-Mode#27]
I can not get syntax highlighting nor indenting to work in enh-ruby-mode. It works fine in ruby-mode, but when enh-ruby-mode is turned on everything is just black text, and auto indent stops working. I am running emacs 24.4.1 on Debian Wheezy, and I installed version 20150312.1458 of enh-ruby-package from melpa archive.

![screenshot from 2015-04-06 23 22 07](https://cloud.githubusercontent.com/assets/584017/7016543/6732bfd4-dcb4-11e4-99d1-7b76b2a46339.png)

**~/.emacs.d/init.el**

``` elisp
(load "package")
(package-initialize)
(add-to-list 'package-archives
             '("melpa" . "http://melpa.milkbox.net/packages/") t)

;; Installs version 20150312.1458 of enh-ruby-package from melpa
(package-refresh-contents)
(package-install 'enh-ruby-mode)

(add-to-list 'load-path "(path-to)/Enhanced-Ruby-Mode") ; must be added after any path containing old ruby-mode
(autoload 'enh-ruby-mode "enh-ruby-mode" "Major mode for ruby files" t)
(add-to-list 'auto-mode-alist '("\\.rb$" . enh-ruby-mode))
(add-to-list 'interpreter-mode-alist '("ruby" . enh-ruby-mode))
```

**Comment by zenspider** [comment]
See #26
