### ISSUE TITLE
special unicode characters in here-doc break highlighting

### ISSUE THREAD

**Issue by nilclass** [jacott/Enhanced-Ruby-Mode#3]
To reproduce:

``` ruby
# encoding: utf-8

class Foo
  HERE = <<DOC
äöü
DOC

  def bar(baz)
  end
end
```

In this case it shifts the colors below the here-doc by the number of umlauts in the doc.

**Comment by jacott** [comment]
Thanks. The bug appears to be with the ruby parser; I have pushed a work-around

**Comment by nilclass** [comment]
great, thanks.
