### ISSUE TITLE
Indentation settings

### ISSUE THREAD

**Issue by Jell** [jacott/Enhanced-Ruby-Mode#7]
I don't seem to get the indentation to work as I want it to.

I want this:

``` ruby
test = {
  a: 1,
  b: 2,
  c: {
    d: 4
  }
}
```

I always get this:

``` ruby
test = {
        a: 1,
        b: 2,
        c: {
            d: 4
           }
        }
```

Even after setting:

``` elisp
(setq ruby-deep-arglist t)
(setq ruby-deep-indent-paren nil)
(setq ruby-hanging-indent-level 2)
```

Am I doing something wrong? Or are those settings simply ignored?

**Comment by jacott** [comment]
Yes, those settings were ignored. They were left in there for compatibility with the original ruby-mode.el.

I have pushed a change which looks at ruby-deep-indent-paren to determine indent style; only t and nil are accepted.

Hope that works for you

**Comment by Jell** [comment]
Great, thanks! Is a full support for all the settings from ruby-mode possible with your implementation?

**Comment by jacott** [comment]
Yep, anything's possible ;)

**Comment by jacott** [comment]
Is there some missing settings that you particularly want?

**Comment by Jell** [comment]
Not at the moment, but I'm guessing others might! :)

Conceptually, it would be great if Enhanced-Ruby-Mode was a 100% compatible drop-in replacement for ruby-mode, so having a full support of the ruby-mode settings would be a first step.

Thanks for your quick fixes by the way!
