### ISSUE TITLE
ruby-end-of-defun does not work

### ISSUE THREAD

**Issue by Jell** [jacott/Enhanced-Ruby-Mode#9]
If I run `M-x ruby-end-of-defun` in this file, where `|` is the position of the cursor:

``` ruby
def te|st
  "test"
end
```

The cursor ends up here:

``` ruby
def test
  "test"
|end
```

Instead of here:

``` ruby
def test
  "test"
end|
```

Even worse, if I run it at this position:

``` ruby
def test
  "test"
e|nd
```

Then the CPU usage goes up to 100% and emacs is frozen in an infinite loop.

**Comment by jacott** [comment]
Fixed. Also fixed bug in ruby-beginning-of-defun.
